version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore: "
    groups:
      experimental-golang-deps:
        patterns:
          - "golang.org/x/*"
